def face(parent):
	parent.tabWidget.setCurrentIndex(1)
	parent.faceWidthX.setText('10')
	parent.faceDepthY.setText('5')
	parent.faceLeft.setText('0')
	parent.faceRear.setText('0')
	parent.faceTop.setText('0')
	parent.faceTool.setText('6')
	parent.faceToolDia.setText('1.0')
	parent.faceRPM.setText('1800')
	parent.faceFeed.setText('50')
	parent.faceStep.setText('75')
	parent.faceSafeZ.setText('0.75')
	parent.faceLeadIn.setText('.5')
	parent.faceCutDepth.setText('-.5')
	parent.faceStepDepth.setText('.125')

def pocket(parent):
	parent.tabWidget.setCurrentIndex(2)
	parent.pocketWidthX.setText('10')
	parent.pocketDepthY.setText('5')
	parent.pocketRadius.setText('1.0')
	parent.pocketLeft.setText('0')
	parent.pocketRear.setText('0')
	parent.pocketTop.setText('0')
	parent.pocketTool.setText('4')
	parent.pocketToolDia.setText('0.5')
	parent.pocketRPM.setText('1800')
	parent.pocketFeed.setText('50')
	parent.pocketStep.setText('50')
	parent.pocketSafeZ.setText('0.75')
	parent.pocketLeadIn.setText('.5')
	parent.pocketCutDepth.setText('-.250')
	parent.pocketStepDepth.setText('.125')

def canned(parent):
	parent.tabWidget.setCurrentIndex(3)
	parent.canToolLE.setText('1')
	parent.canRetractLE.setText('0.250')
	parent.canRpmLE.setText('675')
	parent.canZdepthLE.setText('-1.250')
	parent.canFeedLE.setText('5')
	parent.canCoordPTE.appendPlainText('X1.0 Y-1.0')
	parent.canCoordPTE.appendPlainText('X2.0 Y-1.0')
	parent.canCoordPTE.appendPlainText('X3.0 Y-1.0')
